export type FieldType = 'float' | 'int' | 'bool' | 'enum' | 'command' | 'readonly';
export type FieldProtocol = 'odrive' | 'openffboard';

export interface FieldOption {
  value: string;
  label: string;
}

export interface ConfigField {
  path: string;
  label: string;
  type: FieldType;
  protocol: FieldProtocol;
  description: string;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  defaultValue?: string;
  exampleValue?: string;
  help?: string;
  caution?: string;
  options?: FieldOption[];
  readonly?: boolean;
  groupId?: string;
}

export interface ConfigGroup {
  id: string;
  title: string;
  description: string;
  fields: ConfigField[];
}

const boolOptions: FieldOption[] = [
  { value: 'true', label: 'True' },
  { value: 'false', label: 'False' },
];

const controlModeOptions: FieldOption[] = [
  { value: '0', label: 'Voltage' },
  { value: '1', label: 'Torque' },
  { value: '2', label: 'Velocity' },
  { value: '3', label: 'Position' },
];

const inputModeOptions: FieldOption[] = [
  { value: '0', label: 'Inactive' },
  { value: '1', label: 'Passthrough' },
  { value: '2', label: 'Velocity ramp' },
  { value: '3', label: 'Position filter' },
  { value: '5', label: 'Torque ramp' },
];

const encoderModeOptions: FieldOption[] = [
  { value: '0', label: 'Incremental' },
  { value: '1', label: 'Hall' },
  { value: '257', label: 'SPI ABS AMS' },
  { value: '258', label: 'SPI ABS CUI' },
  { value: '259', label: 'SPI ABS AEAT' },
  { value: '260', label: 'SPI ABS RLS' },
];

const motorTypeOptions: FieldOption[] = [
  { value: '0', label: 'High current BLDC' },
  { value: '2', label: 'Gimbal' },
  { value: '3', label: 'ACIM' },
];

const gpioModeOptions: FieldOption[] = [
  { value: '0', label: 'Disabled' },
  { value: '1', label: 'Button' },
  { value: '2', label: 'Analog axis' },
  { value: '3', label: 'Zero wheel' },
];

export const configGroups: ConfigGroup[] = [
  {
    id: 'psu',
    title: 'PSU / Brake',
    description: 'Power supply and brake resistor limits from the ODrive config.',
    fields: [
      {
        path: 'vbus_voltage',
        label: 'VBUS voltage',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Live DC bus voltage reported by the board.',
      },
      {
        path: 'ibus',
        label: 'IBUS',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Live DC bus current.',
      },
      {
        path: 'brake_resistor_current',
        label: 'Brake resistor current',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Estimated brake resistor current for regen/power monitoring.',
      },
      {
        path: 'config.dc_bus_overvoltage_trip_level',
        label: 'Overvoltage trip',
        type: 'float',
        protocol: 'odrive',
        min: 12,
        max: 60,
        step: 0.1,
        description: 'DC bus voltage where the firmware trips with overvoltage.',
      },
      {
        path: 'config.dc_bus_undervoltage_trip_level',
        label: 'Undervoltage trip',
        type: 'float',
        protocol: 'odrive',
        min: 8,
        max: 48,
        step: 0.1,
        description: 'DC bus voltage where the firmware trips with undervoltage.',
      },
      {
        path: 'config.brake_resistance',
        label: 'Brake resistance',
        type: 'float',
        protocol: 'odrive',
        min: 0.1,
        max: 10,
        step: 0.1,
        description: 'External brake resistor value in ohms.',
      },
      {
        path: 'config.enable_brake_resistor',
        label: 'Enable brake resistor',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enables regenerative braking through the resistor.',
      },
      {
        path: 'config.dc_bus_overvoltage_ramp_start',
        label: 'Brake ramp start',
        type: 'float',
        protocol: 'odrive',
        min: 12,
        max: 60,
        step: 0.1,
        description: 'DC bus voltage where brake resistor duty starts ramping.',
      },
      {
        path: 'config.dc_bus_overvoltage_ramp_end',
        label: 'Brake ramp end',
        type: 'float',
        protocol: 'odrive',
        min: 12,
        max: 60,
        step: 0.1,
        description: 'DC bus voltage where brake resistor reaches full duty.',
      },
      {
        path: 'config.dc_max_positive_current',
        label: 'PSU current max',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 100,
        step: 0.1,
        description: 'Maximum current drawn from the power supply.',
      },
      {
        path: 'config.dc_max_negative_current',
        label: 'Regen current max',
        type: 'float',
        protocol: 'odrive',
        min: -100,
        max: 0,
        step: 0.1,
        description: 'Maximum current returned to the power supply during regen.',
      },
    ],
  },
  {
    id: 'axis',
    title: 'Axis 0',
    description: 'Axis state, startup behavior, and closed-loop defaults.',
    fields: [
      {
        path: 'axis0.current_state',
        label: 'Current state',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Current ODrive axis state.',
      },
      {
        path: 'axis0.requested_state',
        label: 'Requested state',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 16,
        step: 1,
        description: 'Writes a requested ODrive state, such as IDLE or CLOSED_LOOP_CONTROL.',
      },
      {
        path: 'axis0.config.startup_closed_loop_control',
        label: 'Startup closed loop',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Automatically enters closed loop after boot when calibration is valid.',
      },
    ],
  },
  {
    id: 'motor',
    title: 'Motor',
    description: 'Motor calibration, torque constant, and current limits.',
    fields: [
      {
        path: 'axis0.motor.config.current_lim',
        label: 'Current limit',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 60,
        step: 0.1,
        description: 'Maximum phase current allowed by the motor config.',
      },
      {
        path: 'axis0.motor.config.motor_type',
        label: 'Motor type',
        type: 'enum',
        protocol: 'odrive',
        options: motorTypeOptions,
        description: 'ODrive motor type. Use high-current BLDC for most wheel motors.',
      },
      {
        path: 'axis0.motor.config.pole_pairs',
        label: 'Pole pairs',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 100,
        step: 1,
        description: 'Motor magnet pairs. Count magnets and divide by two.',
      },
      {
        path: 'axis0.motor.config.calibration_current',
        label: 'Calibration current',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 20,
        step: 0.1,
        description: 'Current used during motor calibration.',
      },
      {
        path: 'axis0.motor.config.resistance_calib_max_voltage',
        label: 'R calib max voltage',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 24,
        step: 0.1,
        description: 'Maximum voltage used while measuring phase resistance.',
      },
      {
        path: 'axis0.motor.config.torque_constant',
        label: 'Torque constant',
        type: 'float',
        protocol: 'odrive',
        min: 0.01,
        max: 5,
        step: 0.001,
        description: 'Nm/A scaling used to convert requested torque to current.',
      },
      {
        path: 'axis0.motor.config.current_control_bandwidth',
        label: 'Current bandwidth',
        type: 'float',
        protocol: 'odrive',
        min: 10,
        max: 3000,
        step: 1,
        description: 'Current controller bandwidth. Higher is faster but noisier.',
      },
      {
        path: 'axis0.motor.config.current_control_deadband',
        label: 'Current deadband',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Odrive-Wheel idle-noise deadband for the current PI loop.',
      },
      {
        path: 'axis0.motor.config.pre_calibrated',
        label: 'Motor pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skips motor calibration on boot when measured R/L values are valid.',
      },
      {
        path: 'axis0.motor.is_calibrated',
        label: 'Motor calibrated',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'True after resistance and inductance calibration succeeds.',
      },
      {
        path: 'axis0.motor.current_control.Iq_measured',
        label: 'Iq measured',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured quadrature current, useful for saturation and FFB load monitoring.',
      },
    ],
  },
  {
    id: 'encoder',
    title: 'Encoder',
    description: 'Encoder mode, CPR, direction, and calibration flags.',
    fields: [
      {
        path: 'axis0.encoder.config.mode',
        label: 'Encoder mode',
        type: 'enum',
        protocol: 'odrive',
        options: encoderModeOptions,
        description: 'Encoder source used by ODrive.',
      },
      {
        path: 'axis0.encoder.config.cpr',
        label: 'CPR',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 1000000,
        step: 1,
        description: 'Counts per revolution used to scale encoder counts to turns.',
      },
      {
        path: 'axis0.encoder.config.bandwidth',
        label: 'Encoder bandwidth',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 2000,
        step: 1,
        description: 'PLL estimator bandwidth in Hz.',
      },
      {
        path: 'axis0.encoder.config.use_index',
        label: 'Use index Z',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Uses the encoder index pulse for absolute startup reference.',
      },
      {
        path: 'axis0.encoder.config.pre_calibrated',
        label: 'Pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Marks the encoder offset as valid on boot.',
      },
      {
        path: 'axis0.encoder.is_ready',
        label: 'Encoder ready',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'True when ODrive has a valid encoder estimate.',
      },
    ],
  },
  {
    id: 'controller',
    title: 'Controller',
    description: 'Controller mode and torque-mode parameters for FFB operation.',
    fields: [
      {
        path: 'axis0.controller.config.control_mode',
        label: 'Control mode',
        type: 'enum',
        protocol: 'odrive',
        options: controlModeOptions,
        description: 'FFB should normally use Torque mode.',
      },
      {
        path: 'axis0.controller.config.input_mode',
        label: 'Input mode',
        type: 'enum',
        protocol: 'odrive',
        options: inputModeOptions,
        description: 'FFB should normally use Passthrough so input_torque maps directly.',
      },
      {
        path: 'axis0.controller.config.vel_limit',
        label: 'Velocity limit',
        type: 'float',
        protocol: 'odrive',
        min: 0.1,
        max: 100,
        step: 0.1,
        description: 'Maximum velocity limit used by ODrive checks.',
      },
      {
        path: 'axis0.controller.config.enable_vel_limit',
        label: 'Enable vel limit',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enables velocity limit enforcement.',
      },
      {
        path: 'axis0.controller.config.enable_overspeed_error',
        label: 'Overspeed error',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Trips an error when velocity exceeds the configured tolerance.',
      },
      {
        path: 'axis0.controller.config.enable_torque_mode_vel_limit',
        label: 'Torque mode vel clamp',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Usually disabled for FFB so torque is not clamped by velocity.',
      },
      {
        path: 'axis0.controller.input_torque',
        label: 'Input torque',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Current torque setpoint written by the FFB bridge.',
      },
    ],
  },
  {
    id: 'ffb-wheel',
    title: 'FFB Wheel',
    description: 'OpenFFBoard-style wheel parameters persisted by sys.save.',
    fields: [
      {
        path: 'axis.range',
        label: 'Range',
        type: 'float',
        protocol: 'openffboard',
        min: 90,
        max: 2520,
        step: 1,
        description: 'Wheel lock-to-lock angle in degrees.',
      },
      {
        path: 'axis.maxtorque',
        label: 'Max torque',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 20,
        step: 0.1,
        description: 'Torque scale used to convert HID force to Nm.',
      },
      {
        path: 'axis.fxratio',
        label: 'FX ratio',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Global FFB ratio applied before sending torque to ODrive.',
      },
      {
        path: 'axis.invert',
        label: 'Invert wheel',
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        description: 'Inverts wheel direction in HID/FFB space without rewiring motor phases.',
      },
      {
        path: 'axis.idlespring',
        label: 'Idle spring',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Centering spring applied when game FFB is inactive.',
      },
      {
        path: 'axis.axisdamper',
        label: 'Axis damper',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active velocity damping.',
      },
      {
        path: 'axis.axisinertia',
        label: 'Axis inertia',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active acceleration resistance.',
      },
      {
        path: 'axis.axisfriction',
        label: 'Axis friction',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active friction force around motion.',
      },
      {
        path: 'axis.esgain',
        label: 'End-stop spring',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Electronic end-stop spring strength.',
      },
      {
        path: 'axis.esdamp',
        label: 'End-stop damper',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Electronic end-stop damping, independent from spring gain.',
      },
      {
        path: 'axis.maxtorquerate',
        label: 'Torque slew limit',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 65535,
        step: 1,
        description: 'Maximum torque change per millisecond in internal counts. Zero disables.',
      },
      {
        path: 'axis.expo',
        label: 'Expo',
        type: 'int',
        protocol: 'openffboard',
        min: -32767,
        max: 32767,
        step: 1,
        description: 'Non-linear wheel position curve.',
      },
      {
        path: 'axis.exposcale',
        label: 'Expo scale',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 255,
        step: 1,
        description: 'Divisor for the expo curve value.',
      },
    ],
  },
  {
    id: 'ffb-effects',
    title: 'FFB Effects',
    description: 'Master and per-effect gains from the EffectsCalculator.',
    fields: [
      {
        path: 'fx.master',
        label: 'Master gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Global FFB gain.',
      },
      {
        path: 'fx.spring',
        label: 'Spring gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Gain applied to spring condition effects.',
      },
      {
        path: 'fx.damper',
        label: 'Damper gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Gain applied to damper condition effects.',
      },
      {
        path: 'fx.friction',
        label: 'Friction gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Gain applied to friction condition effects.',
      },
      {
        path: 'fx.inertia',
        label: 'Inertia gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Gain applied to inertia condition effects.',
      },
    ],
  },
  {
    id: 'ffb-filters',
    title: 'FFB Filters',
    description: 'Biquad low-pass filter parameters exposed by EffectsCalculator.',
    fields: [
      {
        path: 'fx.filterCfFreq',
        label: 'Constant force frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for constant force.',
      },
      {
        path: 'fx.filterCfQ',
        label: 'Constant force Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Biquad Q factor for constant force.',
      },
      {
        path: 'fx.filterDaFreq',
        label: 'Damper frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for damper effects.',
      },
      {
        path: 'fx.filterDaQ',
        label: 'Damper Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Biquad Q factor for damper effects.',
      },
      {
        path: 'fx.filterFrFreq',
        label: 'Friction frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for friction effects.',
      },
      {
        path: 'fx.filterFrQ',
        label: 'Friction Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Biquad Q factor for friction effects.',
      },
      {
        path: 'fx.filterInFreq',
        label: 'Inertia frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for inertia effects.',
      },
      {
        path: 'fx.filterInQ',
        label: 'Inertia Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Biquad Q factor for inertia effects.',
      },
    ],
  },
  {
    id: 'inputs',
    title: 'Inputs',
    description: 'GPIO joystick inputs exposed as buttons, analog axes, or zero-wheel trigger.',
    fields: [1, 2, 3, 4].flatMap((gpio) => [
      {
        path: `gpio.${gpio}.mode`,
        label: `GPIO ${gpio} mode`,
        type: 'enum',
        protocol: 'openffboard',
        options: gpioModeOptions,
        description: 'Input mode for this GPIO.',
      },
      {
        path: `gpio.${gpio}.idx`,
        label: `GPIO ${gpio} index`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 63,
        step: 1,
        description: 'Button index or analog axis index, depending on mode.',
      },
      {
        path: `gpio.${gpio}.invert`,
        label: `GPIO ${gpio} invert`,
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        description: 'Inverts button or analog direction.',
      },
      {
        path: `gpio.${gpio}.amin`,
        label: `GPIO ${gpio} analog min`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 4095,
        step: 1,
        description: 'Raw ADC minimum used for analog axis calibration.',
      },
      {
        path: `gpio.${gpio}.amax`,
        label: `GPIO ${gpio} analog max`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 4095,
        step: 1,
        description: 'Raw ADC maximum used for analog axis calibration.',
      },
      {
        path: `gpio.${gpio}.cur`,
        label: `GPIO ${gpio} raw`,
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Live raw value for diagnostics and calibration.',
      },
    ] satisfies ConfigField[]),
  },
  {
    id: 'system',
    title: 'System / Telemetry',
    description: 'OpenFFBoard system and ODrive bridge readouts.',
    fields: [
      {
        path: 'sys.swver',
        label: 'Firmware version',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Configurator compatibility firmware version.',
      },
      {
        path: 'sys.hwtype',
        label: 'Hardware type',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Reported Odrive-Wheel hardware type.',
      },
      {
        path: 'sys.heap',
        label: 'Free heap',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'FreeRTOS heap available on the board.',
      },
      {
        path: 'sys.vbusdiv',
        label: 'VBUS divider',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 50,
        step: 1,
        description: 'Runtime voltage divider used for VBUS ADC scaling.',
      },
      {
        path: 'axis.curpos',
        label: 'Wheel position',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Current logical wheel position in degrees.',
      },
      {
        path: 'axis.curspd',
        label: 'Wheel speed',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Current wheel speed in degrees per second.',
      },
      {
        path: 'axis.curtorque',
        label: 'Current FFB torque',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Current internal FFB torque count.',
      },
      {
        path: 'odrv.vbus',
        label: 'ODrive VBUS',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'VBUS exposed by the ODrive bridge.',
      },
      {
        path: 'odrv.maxtorque',
        label: 'Effective max torque',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Estimated effective max torque from motor/current configuration.',
      },
    ],
  },
];

export const flatFields = configGroups.flatMap((group) => group.fields.map((field) => ({ ...field, groupId: group.id })));
