export type FieldType = 'float' | 'int' | 'bool' | 'enum' | 'command' | 'readonly';
export type FieldProtocol = 'odrive' | 'openffboard';

export interface FieldOption {
  value: string;
  label: string;
}

export interface ConfigField {
  path: string;
  label: string;
  type: FieldType;
  protocol: FieldProtocol;
  description: string;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  defaultValue?: string;
  exampleValue?: string;
  help?: string;
  caution?: string;
  options?: FieldOption[];
  readonly?: boolean;
  groupId?: string;
}

export interface ConfigGroup {
  id: string;
  title: string;
  description: string;
  fields: ConfigField[];
}

const boolOptions: FieldOption[] = [
  { value: 'true', label: 'True' },
  { value: 'false', label: 'False' },
];

const controlModeOptions: FieldOption[] = [
  { value: '0', label: 'Voltage' },
  { value: '1', label: 'Torque' },
  { value: '2', label: 'Velocity' },
  { value: '3', label: 'Position' },
];

const inputModeOptions: FieldOption[] = [
  { value: '0', label: 'Inactive' },
  { value: '1', label: 'Passthrough' },
  { value: '2', label: 'Velocity ramp' },
  { value: '3', label: 'Position filter' },
  { value: '5', label: 'Torque ramp' },
];

const encoderModeOptions: FieldOption[] = [
  { value: '0', label: 'Incremental' },
  { value: '1', label: 'Hall' },
  { value: '257', label: 'SPI ABS AMS' },
  { value: '258', label: 'SPI ABS CUI' },
  { value: '259', label: 'SPI ABS AEAT' },
  { value: '260', label: 'SPI ABS RLS' },
];

const motorTypeOptions: FieldOption[] = [
  { value: '0', label: 'High current BLDC' },
  { value: '2', label: 'Gimbal' },
  { value: '3', label: 'ACIM' },
];

const gpioModeOptions: FieldOption[] = [
  { value: '0', label: 'Disabled' },
  { value: '1', label: 'Button' },
  { value: '2', label: 'Analog axis' },
  { value: '3', label: 'Zero wheel' },
];

export const configGroups: ConfigGroup[] = [
  {
    id: 'psu',
    title: 'PSU / Brake',
    description: 'Power supply and brake resistor limits from the ODrive config.',
    fields: [
      {
        path: 'vbus_voltage',
        label: 'VBUS voltage',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Live DC bus voltage reported by the board.',
      },
      {
        path: 'ibus',
        label: 'IBUS',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Live DC bus current.',
      },
      {
        path: 'brake_resistor_current',
        label: 'Brake resistor current',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Estimated brake resistor current for regen/power monitoring.',
      },
      {
        path: 'config.dc_bus_overvoltage_trip_level',
        label: 'Overvoltage trip',
        type: 'float',
        protocol: 'odrive',
        min: 12,
        max: 60,
        step: 0.1,
        description: 'Bus voltage that triggers an overvoltage fault. Set 2–4 V above PSU nominal.',
      },
      {
        path: 'config.dc_bus_undervoltage_trip_level',
        label: 'Undervoltage trip',
        type: 'float',
        protocol: 'odrive',
        min: 8,
        max: 48,
        step: 0.1,
        description: 'Bus voltage that triggers an undervoltage fault. Set just below minimum supply voltage.',
      },
      {
        path: 'config.brake_resistance',
        label: 'Brake resistance',
        type: 'float',
        protocol: 'odrive',
        min: 0.1,
        max: 10,
        step: 0.1,
        description: 'Physical brake resistor value in ohms. Must match exactly — verify with a multimeter.',
      },
      {
        path: 'config.enable_brake_resistor',
        label: 'Enable brake resistor',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enables the brake resistor for regen energy dissipation. Required for sustained FFB sessions.',
      },
      {
        path: 'config.dc_bus_overvoltage_ramp_start',
        label: 'Brake ramp start',
        type: 'float',
        protocol: 'odrive',
        min: 12,
        max: 60,
        step: 0.1,
        description: 'Bus voltage where brake resistor duty begins ramping up. Must be < ramp_end.',
      },
      {
        path: 'config.dc_bus_overvoltage_ramp_end',
        label: 'Brake ramp end',
        type: 'float',
        protocol: 'odrive',
        min: 12,
        max: 60,
        step: 0.1,
        description: 'Bus voltage where brake resistor reaches full 100 % duty. Set = trip_level − 1 V.',
      },
      {
        path: 'config.dc_max_positive_current',
        label: 'PSU current max',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 100,
        step: 0.1,
        description: 'Maximum current the ODrive draws from the power supply. Set ≤ PSU rated current.',
      },
      {
        path: 'config.dc_max_negative_current',
        label: 'Regen current max',
        type: 'float',
        protocol: 'odrive',
        min: -100,
        max: 0,
        step: 0.1,
        description: 'Maximum regen current pushed back into the supply (keep negative). Use −0.1 for non-regen PSUs.',
      },
      {
        path: 'config.max_regen_current',
        label: 'Max regen current',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 100,
        step: 0.1,
        description: 'Maximum regen current into the DC bus. Set 0 when using a non-regen PSU.',
      },
    ],
  },
  {
    id: 'axis',
    title: 'Axis 0',
    description: 'Axis state, startup behavior, and closed-loop defaults.',
    fields: [
      {
        path: 'axis0.current_state',
        label: 'Current state',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Current ODrive axis state.',
      },
      {
        path: 'axis0.requested_state',
        label: 'Requested state',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 16,
        step: 1,
        description: 'ODrive axis state command. 1 = IDLE (safe), 8 = CLOSED_LOOP_CONTROL (FFB active). Never send 3 with wheel mounted.',
      },
      {
        path: 'axis0.config.startup_closed_loop_control',
        label: 'Startup closed loop',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Auto-enters closed-loop after boot. Only enable after motor and encoder are pre_calibrated.',
      },
      {
        path: 'axis0.config.startup_motor_calibration',
        label: 'Startup motor cal',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Run motor R/L calibration automatically on boot when not pre_calibrated.',
      },
      {
        path: 'axis0.config.startup_encoder_offset_calibration',
        label: 'Startup encoder cal',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Run encoder offset calibration on boot when not pre_calibrated.',
      },
      {
        path: 'axis0.config.startup_encoder_index_search',
        label: 'Startup index search',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Search encoder Z index on boot. Only for incremental encoders with index wired.',
      },
    ],
  },
  {
    id: 'motor',
    title: 'Motor',
    description: 'Motor calibration, torque constant, and current limits.',
    fields: [
      {
        path: 'axis0.motor.config.current_lim',
        label: 'Current limit',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 60,
        step: 0.1,
        description: '⚠ Safety-critical. Max phase current = max torque. Set ≤ motor rated current. Formula: current_lim = max_torque_Nm ÷ torque_constant.',
      },
      {
        path: 'axis0.motor.config.motor_type',
        label: 'Motor type',
        type: 'enum',
        protocol: 'odrive',
        options: motorTypeOptions,
        description: 'Motor construction type. High-current BLDC for almost all direct-drive wheel motors.',
      },
      {
        path: 'axis0.motor.config.pole_pairs',
        label: 'Pole pairs',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 100,
        step: 1,
        description: '⚠ Must be exact. Count rotor magnets ÷ 2. Wrong value = failed calibration or erratic torque.',
      },
      {
        path: 'axis0.motor.config.calibration_current',
        label: 'Calibration current',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 20,
        step: 0.1,
        description: 'Current used during R/L measurement. Set to ~25 % of current_lim. Too low = inaccurate calibration.',
      },
      {
        path: 'axis0.motor.config.resistance_calib_max_voltage',
        label: 'R calib max voltage',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 24,
        step: 0.1,
        description: 'Voltage ceiling during resistance measurement. Raise to 6–8 V if calibration fails on high-resistance motors.',
      },
      {
        path: 'axis0.motor.config.torque_constant',
        label: 'Torque constant (Kt)',
        type: 'float',
        protocol: 'odrive',
        min: 0.01,
        max: 5,
        step: 0.001,
        description: '⚠ Critical. Nm/A ratio used to convert torque commands to phase current. Kt = rated_Nm ÷ rated_A or 8.27 ÷ motor_kv.',
      },
      {
        path: 'axis0.motor.config.current_control_bandwidth',
        label: 'Current bandwidth',
        type: 'float',
        protocol: 'odrive',
        min: 10,
        max: 3000,
        step: 1,
        description: 'Current loop speed in rad/s. Higher = crisper FFB feel. Too high = audible oscillation. Start at 100, increase carefully.',
      },
      {
        path: 'axis0.motor.config.requested_current_range',
        label: 'Requested current range',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 60,
        step: 0.1,
        description: 'ADC current sense range in amps. Set slightly above current_lim.',
      },
      {
        path: 'axis0.motor.config.phase_resistance',
        label: 'Phase resistance',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured phase resistance from motor calibration (Ω).',
      },
      {
        path: 'axis0.motor.config.phase_inductance',
        label: 'Phase inductance',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured phase inductance from motor calibration (H).',
      },
      {
        path: 'axis0.motor.config.current_control_deadband',
        label: 'Current deadband',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Suppresses idle hum in the current PI loop. 0 = sharpest response. Raise to 0.02–0.05 only if motor hums when idle.',
      },
      {
        path: 'axis0.motor.config.pre_calibrated',
        label: 'Motor pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skip R/L calibration on boot. Only set true after a successful calibration with valid R/L measurements.',
      },
      {
        path: 'axis0.motor.is_calibrated',
        label: 'Motor calibrated',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'True after resistance and inductance calibration succeeds.',
      },
      {
        path: 'axis0.motor.current_control.Iq_measured',
        label: 'Iq measured',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured quadrature current, useful for saturation and FFB load monitoring.',
      },
    ],
  },
  {
    id: 'encoder',
    title: 'Encoder',
    description: 'Encoder mode, CPR, direction, and calibration flags.',
    fields: [
      {
        path: 'axis0.encoder.config.mode',
        label: 'Encoder mode',
        type: 'enum',
        protocol: 'odrive',
        options: encoderModeOptions,
        description: 'Encoder feedback type. Incremental for standard A/B quadrature; SPI variants for absolute encoders.',
      },
      {
        path: 'axis0.encoder.config.cpr',
        label: 'CPR',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 1000000,
        step: 1,
        description: '⚠ Must match encoder spec (counts/rev = lines/rev × 4 for quadrature). Wrong CPR = incorrect speed and position.',
      },
      {
        path: 'axis0.encoder.config.direction',
        label: 'Direction',
        type: 'int',
        protocol: 'odrive',
        min: -1,
        max: 1,
        step: 1,
        description: 'Encoder count direction: 1 or −1. Use ENCODER_DIR_FIND (state=10) to detect.',
      },
      {
        path: 'axis0.encoder.config.bandwidth',
        label: 'Encoder bandwidth',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 2000,
        step: 1,
        description: 'PLL position/velocity estimator speed. Higher = better FFB tracking. Reduce only if encoder signal is noisy.',
      },
      {
        path: 'axis0.encoder.config.use_index',
        label: 'Use index Z',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enable when encoder has a Z pulse wired. ODrive searches for it on startup before entering closed-loop.',
      },
      {
        path: 'axis0.encoder.config.abs_spi_cs_gpio_pin',
        label: 'ABS SPI CS pin',
        type: 'int',
        protocol: 'odrive',
        min: 0,
        max: 15,
        step: 1,
        description: 'GPIO chip-select for SPI absolute encoders (AS5047 default: 7 on MKS).',
      },
      {
        path: 'axis0.encoder.config.pre_calibrated',
        label: 'Pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skip encoder offset calibration on boot. Only enable after at least one successful calibration cycle.',
      },
      {
        path: 'axis0.encoder.is_ready',
        label: 'Encoder ready',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'True when ODrive has a valid encoder estimate.',
      },
    ],
  },
  {
    id: 'controller',
    title: 'Controller',
    description: 'Controller mode and torque-mode parameters for FFB operation.',
    fields: [
      {
        path: 'axis0.controller.config.control_mode',
        label: 'Control mode',
        type: 'enum',
        protocol: 'odrive',
        options: controlModeOptions,
        description: '⚠ Must be Torque (1) for FFB. Other modes are incompatible with direct torque commands.',
      },
      {
        path: 'axis0.controller.config.input_mode',
        label: 'Input mode',
        type: 'enum',
        protocol: 'odrive',
        options: inputModeOptions,
        description: '⚠ Must be Passthrough (1) for FFB. Routes input_torque directly to the motor with minimum latency.',
      },
      {
        path: 'axis0.controller.config.vel_limit',
        label: 'Velocity limit',
        type: 'float',
        protocol: 'odrive',
        min: 0.1,
        max: 100,
        step: 0.1,
        description: 'Velocity ceiling in turns/s. Only applies when enable_vel_limit is true. Typically disabled for FFB.',
      },
      {
        path: 'axis0.controller.config.enable_vel_limit',
        label: 'Enable vel limit',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: '⚠ Keep false for FFB. Enabling suppresses game forces when the wheel spins fast.',
      },
      {
        path: 'axis0.controller.config.enable_overspeed_error',
        label: 'Overspeed error',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: '⚠ Keep false for FFB. Enabling trips the axis into error during fast steering inputs, freezing the motor.',
      },
      {
        path: 'axis0.controller.config.enable_torque_mode_vel_limit',
        label: 'Torque mode vel clamp',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: '⚠ Must be false for FFB. When true, ODrive injects opposing forces above vel_limit, fighting game effects.',
      },
      {
        path: 'axis0.controller.config.pos_gain',
        label: 'Position gain',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 500,
        step: 0.1,
        description: 'Position PID proportional gain. Ignored in TORQUE mode.',
      },
      {
        path: 'axis0.controller.config.vel_gain',
        label: 'Velocity gain',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 10,
        step: 0.001,
        description: 'Velocity PID proportional gain. Ignored as PID in TORQUE mode; used only if torque-mode vel clamp is enabled.',
      },
      {
        path: 'axis0.controller.config.vel_integrator_gain',
        label: 'Vel integrator gain',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 10,
        step: 0.001,
        description: 'Velocity integrator gain. Ignored in TORQUE mode.',
      },
      {
        path: 'axis0.controller.config.inertia',
        label: 'Inertia',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 10,
        step: 0.001,
        description: 'Load inertia feed-forward (kg·m²). Ignored in TORQUE mode.',
      },
      {
        path: 'axis0.controller.config.anticogging.anticogging_enabled',
        label: 'Anticogging enabled',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Apply anticogging torque map when pre_calibrated is true.',
      },
      {
        path: 'axis0.controller.config.anticogging.pre_calibrated',
        label: 'Anticogging pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skip anticogging calibration on boot. Set after successful axis.anticogcal! run.',
      },
      {
        path: 'axis0.controller.config.anticogging.index',
        label: 'Anticogging index',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Progress index during anticogging calibration (0–3600).',
      },
      {
        path: 'axis0.controller.input_torque',
        label: 'Input torque',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Current torque setpoint written by the FFB bridge.',
      },
    ],
  },
  {
    id: 'ffb-wheel',
    title: 'FFB Wheel',
    description: 'OpenFFBoard-style wheel parameters persisted by sys.save.',
    fields: [
      {
        path: 'axis.range',
        label: 'Range',
        type: 'float',
        protocol: 'openffboard',
        min: 90,
        max: 2520,
        step: 1,
        description: 'Wheel lock-to-lock angle in degrees. Match your simulator steering lock setting for correct 1:1 ratio.',
      },
      {
        path: 'axis.maxtorque',
        label: 'Max torque',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 20,
        step: 0.1,
        description: '⚠ Torque ceiling. HID full-scale maps to this Nm. Set = current_lim × torque_constant. See TorqueCapAdvisor.',
      },
      {
        path: 'axis.fxratio',
        label: 'FX ratio',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Global FFB strength multiplier (0–1). Master volume for FFB without changing motor limits. 0.75 is a safe starting point.',
      },
      {
        path: 'axis.invert',
        label: 'Invert wheel',
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        description: 'Mirrors FFB direction in software. Enable if wheel pulls the wrong way. Does not fix wrong motor phase wiring.',
      },
      {
        path: 'axis.idlespring',
        label: 'Idle spring',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Centering spring active when game FFB is off (menus, paused). 0 = free wheel. ~15 = gentle return-to-center.',
      },
      {
        path: 'axis.axisdamper',
        label: 'Axis damper',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active velocity resistance (like a hydraulic damper). 0 = off. 8–20 = subtle weight. Independent of game.',
      },
      {
        path: 'axis.axisinertia',
        label: 'Axis inertia',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active acceleration resistance (flywheel simulation). 0 = off. 5–20 = realistic mass without killing responsiveness.',
      },
      {
        path: 'axis.axisfriction',
        label: 'Axis friction',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active constant friction (stiction). 0 = off. Use sparingly — high values mask fine FFB textures from the game.',
      },
      {
        path: 'axis.esgain',
        label: 'End-stop spring',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Virtual lock strength when wheel reaches ±range. 0 = no soft stop (dangerous). 40–100 = firm wall.',
      },
      {
        path: 'axis.esdamp',
        label: 'End-stop damper',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Damping at the virtual lock to prevent wheel bounce. Increase if wheel rebounds off the end-stop.',
      },
      {
        path: 'axis.maxtorquerate',
        label: 'Torque slew limit',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 65535,
        step: 1,
        description: 'Max torque change per ms. 0 = disabled (sharpest response). 2–6 smooths abrupt force transitions. High values add latency.',
      },
      {
        path: 'axis.expo',
        label: 'Expo',
        type: 'int',
        protocol: 'openffboard',
        min: -32767,
        max: 32767,
        step: 1,
        description: 'Non-linear HID position curve. 0 = linear. Positive = more center sensitivity. Does not affect FFB forces.',
      },
      {
        path: 'axis.exposcale',
        label: 'Expo scale',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 255,
        step: 1,
        description: 'Divisor for expo curve strength. Higher = softer expo effect. 1 = full expo at the configured axis.expo value.',
      },
    ],
  },
  {
    id: 'ffb-effects',
    title: 'FFB Effects',
    description: 'Master and per-effect gains from the EffectsCalculator.',
    fields: [
      {
        path: 'fx.master',
        label: 'Master gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Global gain applied to ALL effects. 255 = 100 %. Multiplicative with axis.fxratio.',
      },
      {
        path: 'fx.spring',
        label: 'Spring gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for spring condition effects (centering, lane-keep). 0 = disables spring forces from games.',
      },
      {
        path: 'fx.damper',
        label: 'Damper gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for damper condition effects (velocity resistance). High = heavy wheel. Typical 80–180.',
      },
      {
        path: 'fx.friction',
        label: 'Friction gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for friction condition effects (constant resistance). High values dull fine road texture. Typical 50–150.',
      },
      {
        path: 'fx.inertia',
        label: 'Inertia gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for inertia condition effects (mass simulation). High = sluggish, heavy wheel. Typical 50–150.',
      },
    ],
  },
  {
    id: 'ffb-filters',
    title: 'FFB Filters',
    description: 'Biquad low-pass filter parameters exposed by EffectsCalculator.',
    fields: [
      {
        path: 'fx.filterCfFreq',
        label: 'CF filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for constant force (main FFB channel). 0 = bypass. 50–150 Hz = smooth + detailed.',
      },
      {
        path: 'fx.filterCfQ',
        label: 'CF filter Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Q factor for CF filter. 0.707 = flat Butterworth (recommended). >1 = resonant peak — can add lively feel.',
      },
      {
        path: 'fx.filterDaFreq',
        label: 'Damper filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for damper effects. Reduces high-frequency velocity noise in the damper signal.',
      },
      {
        path: 'fx.filterDaQ',
        label: 'Damper filter Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Q factor for damper filter. 0.707 = Butterworth (flat, recommended).',
      },
      {
        path: 'fx.filterFrFreq',
        label: 'Friction filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for friction effects. Smooths sharp friction transitions.',
      },
      {
        path: 'fx.filterFrQ',
        label: 'Friction filter Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Q factor for friction filter. 0.707 = Butterworth (recommended).',
      },
      {
        path: 'fx.filterInFreq',
        label: 'Inertia filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1000,
        step: 0.1,
        description: 'Low-pass cutoff for inertia effects. Smooths jitter from the inertia calculation.',
      },
      {
        path: 'fx.filterInQ',
        label: 'Inertia filter Q',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 10,
        step: 0.01,
        description: 'Q factor for inertia filter. 0.707 = Butterworth (recommended).',
      },
    ],
  },
  {
    id: 'motor-thermistor',
    title: 'Motor thermistor',
    description: 'Offboard NTC temperature monitoring and polynomial coefficients.',
    fields: [
      {
        path: 'axis0.motor.motor_thermistor.config.enabled',
        label: 'Thermistor enabled',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enable motor temperature monitoring via external NTC. Use NTC calculator for polynomial coefficients.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.gpio_pin',
        label: 'NTC GPIO pin',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 8,
        step: 1,
        description: 'GPIO for NTC analog input. Requires external 10kΩ pull-up to 3.3V.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_0',
        label: 'Poly coefficient 0',
        type: 'float',
        protocol: 'odrive',
        description: 'Highest-order coefficient of T(V) polynomial. Use NTC calculator.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_1',
        label: 'Poly coefficient 1',
        type: 'float',
        protocol: 'odrive',
        description: 'Polynomial coefficient c1.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_2',
        label: 'Poly coefficient 2',
        type: 'float',
        protocol: 'odrive',
        description: 'Polynomial coefficient c2.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_3',
        label: 'Poly coefficient 3',
        type: 'float',
        protocol: 'odrive',
        description: 'Lowest-order coefficient c3.',
      },
    ],
  },
  {
    id: 'inputs',
    title: 'Inputs',
    description: 'GPIO joystick inputs exposed as buttons, analog axes, or zero-wheel trigger.',
    fields: [1, 2, 3, 4].flatMap((gpio) => [
      {
        path: `gpio.${gpio}.mode`,
        label: `GPIO ${gpio} mode`,
        type: 'enum',
        protocol: 'openffboard',
        options: gpioModeOptions,
        description: 'Input mode for this GPIO.',
      },
      {
        path: `gpio.${gpio}.idx`,
        label: `GPIO ${gpio} index`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 63,
        step: 1,
        description: 'Button index or analog axis index, depending on mode.',
      },
      {
        path: `gpio.${gpio}.invert`,
        label: `GPIO ${gpio} invert`,
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        description: 'Inverts button or analog direction.',
      },
      {
        path: `gpio.${gpio}.amin`,
        label: `GPIO ${gpio} analog min`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 4095,
        step: 1,
        description: 'Raw ADC minimum used for analog axis calibration.',
      },
      {
        path: `gpio.${gpio}.amax`,
        label: `GPIO ${gpio} analog max`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 4095,
        step: 1,
        description: 'Raw ADC maximum used for analog axis calibration.',
      },
      {
        path: `gpio.${gpio}.cur`,
        label: `GPIO ${gpio} raw`,
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Live raw value for diagnostics and calibration.',
      },
    ] satisfies ConfigField[]),
  },
  {
    id: 'live',
    title: 'Live telemetry',
    description: 'Read-only runtime values for telemetry, dashboard, and debug. Not shown in config editors.',
    fields: [
      {
        path: 'axis.curpos',
        label: 'Wheel position',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'deg',
        description: 'Current wheel angle in degrees.',
      },
      {
        path: 'axis.curspd',
        label: 'Wheel speed',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'deg/s',
        description: 'Current wheel angular velocity.',
      },
      {
        path: 'axis.curtorque',
        label: 'FFB torque',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Raw FFB torque magnitude from OpenFFBoard (use diag T for Nm in charts).',
      },
      {
        path: 'odrv.vbus',
        label: 'VBUS (OpenFFBoard)',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'V',
        description: 'DC bus voltage via OpenFFBoard ADC scaling.',
      },
      {
        path: 'odrv.maxtorque',
        label: 'ODrive max torque',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'Nm',
        description: 'Effective torque ceiling reported by the FFB bridge.',
      },
    ],
  },
  {
    id: 'system',
    title: 'System',
    description: 'Board identity and one configurable system parameter. Live telemetry (position, torque, VBUS) is in the Debug and Observe pages.',
    fields: [
      {
        path: 'sys.swver',
        label: 'Firmware version',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Firmware version string reported by the board.',
      },
      {
        path: 'sys.hwtype',
        label: 'Hardware type',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Hardware variant string (e.g. ODrive-Wheel).',
      },
      {
        path: 'sys.heap',
        label: 'Free heap (bytes)',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'FreeRTOS heap remaining. A value below ~4 kB may cause instability.',
      },
      {
        path: 'sys.vbusdiv',
        label: 'VBUS divider',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 50,
        step: 1,
        unit: 'V',
        defaultValue: '10',
        exampleValue: '10',
        description: '⚠ Hardware parameter. ADC voltage divider ratio. Wrong value = incorrect VBUS readings and broken protection thresholds. Only change if board uses non-standard resistors.',
      },
    ],
  },
];

export const flatFields = configGroups.flatMap((group) => group.fields.map((field) => ({ ...field, groupId: group.id })));
